name: Test Matrix - Run Shell Scripts

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to run scripts against'
        required: true
        default: 'ALL'
        type: choice
        options:
          - DEV
          - QA
          - PROD
          - ALL

jobs:

  run-dev:
    if: ${{ inputs.environment == 'DEV' || inputs.environment == 'ALL' }}
    name: Run Scripts in DEV
    runs-on: ubuntu-latest
    environment: DEV
    strategy:
      matrix:
        applications: [app-1, app-2, app-3, app-4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script in DEV
        run: |
          chmod +x ./${{ matrix.applications }}/${{ matrix.applications }}.sh
          echo "Running ${{ matrix.applications }}.sh in DEV"
          ./${{ matrix.applications }}/${{ matrix.applications }}.sh DEV

  run-qa:
    if: ${{ inputs.environment == 'QA' || inputs.environment == 'ALL' }}
    name: Run Scripts in QA
    runs-on: ubuntu-latest
    environment: QA
    strategy:
      matrix:
        applications: [app-1, app-2, app-3, app-4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script in QA
        run: |
          chmod +x ./${{ matrix.applications }}/${{ matrix.applications }}.sh
          echo "Running ${{ matrix.applications }}.sh in QA"
          ./${{ matrix.applications }}/${{ matrix.applications }}.sh QA

  run-prod:
    if: ${{ inputs.environment == 'PROD' || inputs.environment == 'ALL' }}
    name: Run Scripts in PROD
    runs-on: ubuntu-latest
    environment: PROD
    strategy:
      matrix:
        applications: [app-1, app-2, app-3, app-4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script in PROD
        run: |
          chmod +x ./${{ matrix.applications }}/${{ matrix.applications }}.sh
          echo "Running ${{ matrix.applications }}.sh in PROD"
          ./${{ matrix.applications }}/${{ matrix.applications }}.sh PROD
