name: Deploy Apps

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select one app to run'
        required: true
        default: 'app-1'
        type: choice
        options:
          - app-1
          - app-2
          - app-3
          - app-4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo selected app message
        run: |
          case "${{ github.event.inputs.app }}" in
            app-1)
              echo "Hello world"
              ;;
            app-2)
              echo "How are you"
              ;;
            app-3)
              echo "Good day"
              ;;
            app-4)
              echo "Sunny day"
              ;;
            *)
              echo "Unknown app"
              ;;
          esac
