name: Test Matrix - Run Shell Scripts

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to run scripts against'
        required: true
        default: 'ALL'
        type: choice
        options:
          - DEV
          - QA
          - PROD
          - ALL
      applications:
        description: 'Choose applications to run scripts for'
        required: false
        type: choice
        options:
          - app-1
          - app-2
          - app-3
          - app-4
          - other
        default: 'app-1,app-2,app-3,app-4'
      other-applications:
        description: 'Comma separated list of other applications (optional
