name: Test Matrix - Run Shell Scripts

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to run scripts against'
        required: true
        default: 'ALL'
        type: choice
        options:
          - DEV
          - QA
          - PROD
          - ALL

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        applications: [app-1, app-2, app-3, app-4]
        environments: [DEV, QA, PROD]

    # Skip if input is not ALL and doesn't match matrix environment
    continue-on-error: false
    steps:
      - name: Skip unwanted environments unless ALL is selected
        if: ${{ inputs.environment != 'ALL' && matrix.environments != inputs.environment }}
        run: echo "Skipping ${{ matrix.environments }} as it's not selected."

      - name: Checkout code
        if: ${{ inputs.environment == 'ALL' || matrix.environments == inputs.environment }}
        uses: actions/checkout@v3

      - name: Run shell script
        if: ${{ inputs.environment == 'ALL' || matrix.environments == inputs.environment }}
        run: |
          chmod +x ./${{ matrix.applications }}/${{ matrix.applications }}.sh
          echo "Running ${{ matrix.applications }}.sh for environment: ${{ matrix.environments }}"
          ./${{ matrix.applications }}/${{ matrix.applications }}.sh ${{ matrix.environments }}
