name: Test Matrix - Run Shell Scripts

on:
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        applications: [app-1, app-2, app-3, app-4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shell script
        run: |
          chmod +x ./${{ matrix.applications }}.sh
          echo "Running ${{ matrix.applications }}.sh"
          ./$(echo "${{ matrix.applications }}").sh
